<?php

namespace App\Http\Controllers;

use Plugs\Base\Controller\Controller;
use Psr\Http\Message\ResponseInterface;

/**
 * HomeController
 *
 * Generated by Plugs Framework Installer
 * @created 2026-01-22 04:36:59
 */
class HomeController extends Controller
{
    /**
     * Display Home Page
     */
    public function index(): ResponseInterface
    {
        return $this->view('home.index', [
            'title' => 'Welcome to My Plugs App',
            'message' => 'Your Plugs Framework application is ready!',
        ]);
    }
}
