<?php

namespace App\Http\Controllers;

use Plugs\Base\Controller\Controller;

/**
 * PlugsController
 *
 * Generated by ThePlugs Console
 * @created 2026-01-17 22:11:43
 */
class PlugsController extends Controller
{
    /**
     * Display Plugs Page
     */
    public function index()
    {
        return $this->view('plugs.index', [
            'title' => 'Plugs Framework Page',
        ]);
    }
}
