<?php

namespace App\Controllers;

use Plugs\Base\Controller\Controller;
use Psr\Http\Message\ResponseInterface;

/**
 * AdminController
 *
 * Generated by ThePlugs Console
 * @created 2025-12-22 01:05:30
 */
class AdminController extends Controller
{
    /**
     * Display Admin Dashboard Page
     */
    public function dashboard(): ResponseInterface
    {
        return $this->view('admin.dashboard', [
            'title' => 'Welcome to Trees Framework',
        ]);
    }
}
