<?php

namespace App\Controllers;

use Plugs\Base\Controller\Controller;
use Psr\Http\Message\ResponseInterface;

/**
 * HomeController
 *
 * Generated by ThePlugs Console
 * @created 2025-10-19 21:49:30
 */
class HomeController extends Controller
{
    /**
     * Display Home Page
     */
    public function index(): ResponseInterface
    {
        return $this->view('home.index', [
            'title' => 'Welcome to Trees Framework',
            'message' => 'A secure, scalable PHP MVC framework',
            'username' => 'JohnDoe',
        ]);
    }
}
